### ISSUE TITLE
Meta Information Goals

### ISSUE THREAD

**Issue by SmallJoker** [CERN/CTW#29]
In order to understand our own project's flow, an extended README is really needed.
Required contents: (sorted by priority, most important first)
- [ ] Link or image of technology tree
- [ ] Link or image to the technology researching process (draw.io image?)
  - [ ] more detailed explanation of how to research
- [ ] Era description: how to advance? Requirements? Benefits of advancing?
- [ ] More development information. Linking to or explaining:
  - [ ] cheatengine
  - [ ] in-game tech tree visualization
  - [ ] any other administrative features you know
- [ ] Game concept description (copy-paste and refresh from readthedocs)
