### ISSUE TITLE
TODO: Various gameplay improvements

### ISSUE THREAD

**Issue by SmallJoker** [CERN/CTW#56]
- [ ] Inventory
  - [ ] Show missing resources until next technology
  - [ ] Help page with dropdowns - file-based help files
    - Language dropdown
    - Topic dropdown
- [x] Teams
  - [x] Team colors in chat (like in CTF)
  - [ ] ~Default team-internal chat + `/all`~ -> `/t` exists. Good enough?
